name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Flutter environment
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run analyzer to check for code quality
      - name: Run Flutter Analyze
        run: flutter analyze

      # Run tests
      - name: Run Flutter Tests
        run: flutter test
